PNG_HEADER = b"\x89PNG\r\n\x1a\n"
PNG_IEND = b"IEND"

FFMPEG_CMD = "ffmpeg"

DEFAULT_GIF_COLORS = 64

DEFAULT_VIDEO_CODEC = "libx264"
DEFAULT_VIDEO_PRESET = "medium"
DEFAULT_VIDEO_CRF = 28
DEFAULT_VIDEO_THREADS = 4

DEFAULT_THRESHOLD = 80.0
DEFAULT_MAX_FRAMES = 30
DEFAULT_PADDING = 1
DEFAULT_COLOR = "black"
DEFAULT_BG_COLOR = (0, 0, 0)  # 黑色
DEFAULT_DURATION = 3.0
DEFAULT_FPS = 10
DEFAULT_TARGET_SIZE_MB = 5.0
